#!/usr/bin/python

import sys
import json

# Input is from sersec-summary
serials = json.loads(sys.stdin.read())

class Combiner(object):
    def __init__(self, s):
        self.d = {}
        self.d['name'] = s['name']
        self.d['total-cycles'] = s['total-cycles']
        self.d['total-instructions'] = s['total-instructions']
        self.d['benchmark-fraction'] = s['benchmark-fraction']
        self.d['coherence-miss'] = s['coherence-miss']
        self.d['acquires'] = s['acquires']

    def combine(self, s):
        self.d['total-cycles'] += s['total-cycles']
        self.d['total-instructions'] += s['total-instructions']
        self.d['benchmark-fraction'] += s['benchmark-fraction']
        self.d['coherence-miss'] += s['coherence-miss']
        self.d['acquires'] += s['acquires']

combine = {}
order = []
for s in serials:
    name = s['name']
    if not name in combine:
        combine[name] = Combiner(s)
        order.append(combine[name].d)
    else:
        combine[name].combine(s)

print json.dumps(order, indent=2)
