#!/usr/bin/python

import sys
import json
import numpy

# Input is from sersec-sort
serials = json.loads(sys.stdin.read())
summary = []
for s in serials:
    summary.append({
            'name'               : s['name'], 
            'total-instructions' : s['total-instructions'],
            'total-cycles'       : s['total-cycles'],
            'load-std'           : numpy.std(s['per-cpu-percent']),
            'benchmark-fraction' : s['benchmark-fraction'],
            'coherence-miss'     : s['coherence-miss'],
            'acquires'           : s['acquires']
            })
print json.dumps(summary, indent=2)
