#!/usr/bin/python

import sys
import json

MISS_PENALTY = 250

j = json.load(sys.stdin)
extra = 0
for s in j["serial-sections"]:
    extra += s["coherence-miss"] * MISS_PENALTY
    s["total-cycles"] = (s["total-instructions"] +
                         (s["coherence-miss"] * MISS_PENALTY))
    for p in s["per-acquire-pc"]:
        p["total-cycles"] = (p["total-instructions"] +
                             (p["coherence-miss"] * MISS_PENALTY))

summary = j["summary"]
totalCycles = summary["total-instructions"] + extra
summary["total-cycles"] = totalCycles

for s in j["serial-sections"]:
    s["benchmark-fraction"] = float(s["total-cycles"]) / float(totalCycles)
    for p in s["per-acquire-pc"]:
        p["benchmark-fraction"] = float(p["total-cycles"]) / float(totalCycles)

json.dump(j, sys.stdout, indent=2)
